fullnameOverride: bao-unsealer

injector:
  enabled: false

server:
  image:
    tag: "2.7.0"
  dataStorage:
    enabled: true
    size: 1Gi
  standalone:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        tls_disable     = 1          # Lab! Produktion: TLS
        address         = "[::]:8200"
        cluster_address = "[::]:8201"
      }

      storage "pebbledb" {
        path = "/openbao/data/pebbledb"
      }
