apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: webshop-all
  namespace: webshop
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: openbao
  target:
    name: webshop-all
  dataFrom:
    - extract:
        key: webshop/config
