pipeline {
  agent any
  options {
    timeout(time: 10, unit: 'MINUTES')
    disableConcurrentBuilds()
    buildDiscarder(logRotator(numToKeepStr: '20'))
  }
  stages {
    stage('Dockerfile-Check') {
      steps {
        sh 'test -f Dockerfile'
        // Mini-Regel: Das Image muss als non-root User laufen
        sh 'grep -q "^USER 10001" Dockerfile'
      }
    }
    stage('Info') {
      steps {
        sh 'git log -1 --oneline'
        sh 'sha256sum requirements.txt'
      }
    }
  }
  post {
    always {
      echo "Build ${env.BUILD_NUMBER}: ${currentBuild.currentResult}"
    }
  }
}
