# Pi-hole (v6: misc.etc_dnsmasq_d=true) oder dnsmasq: /etc/dnsmasq.d/
# Wildcard: alle *.apps.lab.internal -> Envoy Gateway
address=/apps.lab.internal/10.10.20.100
# spezifischer gewinnt: *.cilium.apps.lab.internal -> Cilium-Gateway
address=/cilium.apps.lab.internal/10.10.20.101
address=/rke2.lab.internal/10.10.20.10
