# EnvoyProxy fuer Gateway infra/web auf RKE2 (Tag 9, erweitert an Tag 10-12)
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: web-proxy
  namespace: infra
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: LoadBalancer
        externalTrafficPolicy: Cluster   # Pflicht mit Cilium L2 (kein Local)
        annotations:
          lbipam.cilium.io/ips: 10.10.20.100
