apiVersion: v1
kind: LimitRange
metadata:
  name: defaults
  namespace: ki-models
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        memory: 512Mi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ki-models
  namespace: ki-models
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 6Gi
    limits.memory: 8Gi
    persistentvolumeclaims: "5"
