- name: Konfigdatei config.yaml schreiben
  ansible.builtin.template:
    src: config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    mode: "0600"
  notify: Restart rke2-agent

- name: Dienst rke2-agent starten
  ansible.builtin.systemd_service:
    name: rke2-agent
    enabled: true
    state: started
