apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-demo-app-supply-chain
spec:
  webhookTimeoutSeconds: 30
  rules:
    - name: signatur-und-sbom
      match:
        any:
          - resources:
              kinds: ["Pod"]
              namespaces: ["demo"]
      verifyImages:
        - imageReferences: ["reg-ziel:5000/*"]
          failureAction: Enforce
          mutateDigest: true
          verifyDigest: true
          required: true
          attestors:
            - entries:
                - keys:
                    publicKeys: PLATZHALTER
                    rekor:
                      ignoreTlog: true
                    ctlog:
                      ignoreSCT: true
          attestations:
            - type: https://cyclonedx.org/bom
              attestors:
                - entries:
                    - keys:
                        publicKeys: PLATZHALTER
                        rekor:
                          ignoreTlog: true
                        ctlog:
                          ignoreSCT: true
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-image-registries
spec:
  rules:
    - name: nur-zielregistry
      match:
        any:
          - resources:
              kinds: ["Pod"]
              namespaces: ["demo"]
      validate:
        failureAction: Enforce
        message: "Nur freigegebene Images aus reg-ziel:5000 sind erlaubt."
        pattern:
          spec:
            containers:
              - image: "reg-ziel:5000/*"
    - name: keine-quarantaene
      match:
        any:
          - resources:
              kinds: ["Pod"]
              namespaces: ["demo"]
      validate:
        failureAction: Enforce
        message: "Images aus der Quarantäne dürfen nicht laufen."
        pattern:
          spec:
            containers:
              - image: "!reg-ziel:5000/quarantaene/*"
