apiVersion: v1
kind: Pod
metadata: {name: latest, namespace: shop, labels: {app: t}}
spec:
  containers:
    - name: web
      image: nginxinc/nginx-unprivileged:latest
      resources: {requests: {cpu: 10m, memory: 16Mi}, limits: {memory: 64Mi}}
---
apiVersion: v1
kind: Pod
metadata: {name: notag, namespace: shop, labels: {app: t}}
spec:
  containers:
    - name: web
      image: kind-registry:5000/shop/web
      resources: {requests: {cpu: 10m, memory: 16Mi}, limits: {memory: 64Mi}}
---
apiVersion: v1
kind: Pod
metadata: {name: quay, namespace: shop, labels: {app: t}}
spec:
  containers:
    - name: web
      image: quay.io/prometheus/busybox:glibc
      resources: {requests: {cpu: 10m, memory: 16Mi}, limits: {memory: 64Mi}}
---
apiVersion: v1
kind: Pod
metadata: {name: nores, namespace: shop, labels: {app: t}}
spec:
  containers:
    - name: web
      image: nginxinc/nginx-unprivileged:1.31-alpine
---
apiVersion: v1
kind: Pod
metadata: {name: digest, namespace: shop, labels: {app: t}}
spec:
  containers:
    - name: web
      image: "kind-registry:5000/shop/web@sha256:\
        33594ea8c022029e6607bafee25871d224b5f7ca6e17c68d187b68718513a5b1"
      resources: {requests: {cpu: 10m, memory: 16Mi}, limits: {memory: 64Mi}}
