apiVersion: cli.kyverno.io/v1alpha1
kind: Value
metadata:
  name: values
namespaceSelector:
  - name: shop
    labels:
      guard-lab: demo
  - name: tenant-a
    labels:
      guard-lab: demo
  - name: default
    labels:
      kubernetes.io/metadata.name: default
