#!/usr/bin/env bash
# Provision the domain on first start, then run Samba in the foreground.
set -euo pipefail

REALM="${AD_REALM:-MERIDIAN.TEST}"
DOMAIN="${AD_DOMAIN:-MERIDIAN}"
PASS="${AD_ADMIN_PASSWORD:?AD_ADMIN_PASSWORD must be set}"

if [ ! -f /var/lib/samba/private/sam.ldb ]; then
  echo "provisioning $REALM - this takes about a minute"

  # The packaged smb.conf is for a file server and blocks provisioning.
  rm -f /etc/samba/smb.conf

  # posix:eadb puts extended attributes in a tdb instead of on the
  # filesystem. A container filesystem refuses the security.* attributes
  # Samba wants for NT ACLs, and provisioning then fails with
  # NT_STATUS_ACCESS_DENIED from set_nt_acl - a message that says nothing
  # about extended attributes and sends everybody looking at permissions.
  samba-tool domain provision \
    --option="posix:eadb=/var/lib/samba/eadb.tdb" \
    --use-rfc2307 \
    --realm="$REALM" \
    --domain="$DOMAIN" \
    --server-role=dc \
    --dns-backend=SAMBA_INTERNAL \
    --adminpass="$PASS"

  # Forward anything that is not ours, so the container can still
  # resolve the outside world.
  sed -i 's/^\(\s*\)dns forwarder = .*/\1dns forwarder = 1.1.1.1/' \
    /etc/samba/smb.conf || true

  cp /var/lib/samba/private/krb5.conf /etc/krb5.conf
  echo "provisioned"
else
  echo "domain already provisioned; starting"
fi

# Serve LDAPS with the certificate Chapter 2 issued, not with Samba's
# own autogenerated one. Applied on every start so that a reissued
# certificate is picked up without reprovisioning the domain.
if [ -f /pki/dc.crt ]; then
  # Samba refuses a TLS key it does not own - "owner uid 1000 should be
  # 0 ... This is known as CVE-2013-4476" - and then the LDAP task fails
  # to start at all. On macOS the bind mount presents everything as
  # root and the check passes; on Linux the real owner shows through and
  # it does not. Copy rather than mount, so the lab behaves the same on
  # both.
  mkdir -p /var/lib/samba/tls
  cp /pki/dc.crt /pki/dc.key /pki/ca.crt /var/lib/samba/tls/
  chown root:root /var/lib/samba/tls/*
  chmod 600 /var/lib/samba/tls/dc.key
  chmod 644 /var/lib/samba/tls/dc.crt /var/lib/samba/tls/ca.crt

  if ! grep -q 'tls certfile' /etc/samba/smb.conf; then
    sed -i '/^\[global\]/a\
\ttls enabled = yes\
\ttls certfile = /var/lib/samba/tls/dc.crt\
\ttls keyfile = /var/lib/samba/tls/dc.key\
\ttls cafile = /var/lib/samba/tls/ca.crt' /etc/samba/smb.conf
  fi
  echo "LDAPS uses the Meridian certificate"
fi

exec samba -i --debuglevel=1
